# Generated by Django 3.0.1 on 2019-12-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('mobilenumber', models.CharField(max_length=15)),
                ('message', models.CharField(max_length=160)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
