# Generated by Django 3.0.1 on 2019-12-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sm',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='sm',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
