# Generated by Django 3.0.1 on 2020-07-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='api_url',
            field=models.CharField(default='http://impruvitsolutions.com:8000/sms/', max_length=512),
        ),
    ]
