# Generated by Django 3.0.1 on 2020-07-07 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_device_api_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='api_url',
        ),
    ]
